# Generated by Django 3.2.12 on 2022-03-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAdminQueryManagement', '0003_alter_querytype_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryType',
            new_name='QueryTypes',
        ),
    ]
