# Generated by Django 3.2.12 on 2022-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
