# Generated by Django 4.0.1 on 2022-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPIs', '0002_userdonations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonations',
            name='paymentAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdonations',
            name='paymentStatus',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'canceled'), (4, 'failed')], default=2),
        ),
    ]
