# Generated by Django 3.2.12 on 2022-03-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPIs', '0003_alter_userdonations_paymentamount_and_more'),
        ('authAPIs', '0003_alter_userdonations_paymentstatus'),
    ]

    operations = [
    ]
