# Generated by Django 3.2.12 on 2022-03-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPIs', '0004_merge_20220329_1148'),
        ('authAPIs', '0004_merge_20220329_1230'),
    ]

    operations = [
    ]
