# Generated by Django 4.0.1 on 2022-03-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPIs', '0005_merge_20220330_0645'),
        ('authAPIs', '0005_merge_20220330_1140'),
    ]

    operations = [
    ]
